import Head from "next/head";
import styles from "../styles/Home.module.css";
import { nanoid } from "nanoid";
import { useEffect, useState } from "react";
import { useCursorLocation } from "../src/hooks/useCursorLocation";

export default function Home() {
  const [userId, setUserId] = useState("");
  useEffect(() => {
    if (localStorage.getItem("userid"))
      setUserId(localStorage.getItem("userid"));
    else localStorage.setItem("userid", nanoid());
  }, []);
  const { location, isConnected, users } = useCursorLocation(userId);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        USER ID:- {userId} | Socket:-{" "}
        {isConnected ? "connected" : "disconnected"}
        <span
          className={styles.cursor}
          style={{ top: location.y, left: location.x }}
          title={userId}
        >
          {userId}
        </span>
        {Object.keys(users).map((key) => (
          <span
            key={key}
            className={styles.cursor}
            style={{ top: users[key].y, left: users[key].x }}
            title={userId}
          >
            {key}
          </span>
        ))}
      </main>
    </div>
  );
}
